name: Reusable Spring Boot CI/CD

on:
  workflow_call:
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
      ECR_URL:
        required: true

jobs:
  springboot:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build Spring Boot App
        run: mvn clean install --no-transfer-progress

      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - uses: aws-actions/amazon-ecr-login@v1

      - name: Build & Push Docker Image
        run: |
          docker build -t springboot-app .
          docker tag springboot-app:latest ${{ secrets.ECR_URL }}:${{ github.sha }}
          docker tag springboot-app:latest ${{ secrets.ECR_URL }}:latest
          docker push ${{ secrets.ECR_URL }}:${{ github.sha }}
          docker push ${{ secrets.ECR_URL }}:latest
