apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - rolearn: {{ .Values.node_role_arn }}
      username: system:node:{{EC2PrivateDNSName}}
      groups:
        - system:bootstrappers
        - system:nodes
    - rolearn: {{ .Values.master_role_arn }}
      username: eks-master
      groups:
        - system:masters
  mapUsers: |
{{- range .Values.users }}
    - userarn: {{ .user_arn }}
      username: {{ .username }}
      groups:
{{- range .groups }}
        - {{ . }}
{{- end }}
{{- end }}
