name: Reusable Terraform Deployment

on:
  workflow_call:
    inputs:
      tf_directory:
        required: true
        type: string
    secrets:
      AWS_REGION:
        required: true
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
      TF_STATE_S3_BUCKET:
        required: true
      TF_STATE_FILE_KEY:
        required: true
      TF_STATE_DYNAMODB_TABLE:
        required: true
      S3_AWS_REGION:
        required: true
      AWS_ACCOUNT_ID:
        required: true

jobs:
  terraform:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ inputs.tf_directory }}

    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.3

      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Terraform Init
        run: |
          terraform init \
            -backend-config="bucket=${{ secrets.TF_STATE_S3_BUCKET }}" \
            -backend-config="key=${{ secrets.TF_STATE_FILE_KEY }}" \
            -backend-config="region=${{ secrets.S3_AWS_REGION }}" \
            -backend-config="dynamodb_table=${{ secrets.TF_STATE_DYNAMODB_TABLE }}"

      - name: Terraform Plan & Apply
        run: |
          terraform plan -out=tfplan
          terraform apply -auto-approve tfplan
