name: Spring Boot CI/CD to Amazon ECR

on:
  workflow_dispatch:

env:
  AWS_REGION: ap-south-1
  ECR_URL: ${{ secrets.ECR_URL }}

jobs:
  build-and-push:
    name: Build and Push Docker Image to ECR
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build Spring Boot JAR
        run: mvn clean install --no-transfer-progress

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build Docker Image
        run: docker build -t springboot-app .

      - name: Tag and Push Docker Image to ECR
        run: |
          docker tag springboot-app:latest $ECR_URL:${{ github.sha }}
          docker tag springboot-app:latest $ECR_URL:latest
          docker push $ECR_URL:${{ github.sha }}
          docker push $ECR_URL:latest
